### ISSUE TITLE
Reference the Packet hardware supporting the project

### ISSUE THREAD

**Issue by vielmetti** [rudyjantz/beacons#1]
We'd love it if somewhere in the output of this project (whatever it becomes!) has a reference to the Packet and Works on Arm support. 

The corresponding item in the Works on Arm cluster project is https://github.com/WorksOnArm/cluster/issues/61 for reference.

**Comment by portersrc** [comment]
Absolutely. We'll bake it into the README and acknowledge you guys if we get a publication from it. I'm already spouting off about it to friends, too. Thanks, Ed!
